### ISSUE TITLE
Visited link colour contrast too low

### ISSUE THREAD

**Issue by ArcticEcho** [SOBotics/Reports#5]
It is just me, or could the contrast of visited links do with being boosted a little? (Especially for the dark theme.)

**Comment by ArtOfCode-** [comment]
[Yep](https://webaim.org/resources/contrastchecker/?fcolor=3464B7&bcolor=1A1A1A). Current colors only pass WCAG 2.0 AA, and only on large text. Ideally it should pass everything down to AAA for small text, but I tend to aim for AA on small text and AAA on large text.

**Comment by ArcticEcho** [comment]
All link colours now pass WCAG 2.0 AA for normal text.
